// src/data/organData.js
const organData = {
  nasopharynx: { name: "Nasopharynx", function: "Passage for air from nose to throat", location: "Upper throat behind nose", color: "#FFB347" },
  oralCavity: { name: "Oral Cavity", function: "Ingestion, speech, and breathing", location: "Mouth", color: "#FF6961" },
  kidney: { name: "Kidney", function: "Filters blood and produces urine", location: "Abdomen", color: "#77DD77" },
  testis: { name: "Testis", function: "Produces sperm and testosterone", location: "Scrotum", color: "#CBAACB" },
  eye: { name: "Eye", function: "Vision", location: "Head", color: "#779ECB" },
  lung: { name: "Lung", function: "Breathing and oxygen exchange", location: "Chest", color: "#AEC6CF" },
  heart: { name: "Heart", function: "Pumps blood", location: "Chest", color: "#FF6961" },
  brain: { name: "Brain", function: "Controls body functions and cognition", location: "Head", color: "#FFD700" },
  breast: { name: "Breast", function: "Produces milk", location: "Chest", color: "#FFB6C1" },
  thyroid: { name: "Thyroid", function: "Regulates metabolism", location: "Neck", color: "#FFB347" },
  adrenalGland: { name: "Adrenal Gland", function: "Produces hormones like adrenaline", location: "Above kidneys", color: "#CBAACB" },
  pancreas: { name: "Pancreas", function: "Regulates blood sugar", location: "Abdomen", color: "#77DD77" },
  femur: { name: "Femur", function: "Supports weight and allows movement", location: "Thigh", color: "#D1B280" },
  circulatorySystem: { name: "Circulatory System", function: "Transports blood", location: "Whole body", color: "#FF6961" },
  esophagus: { name: "Esophagus", function: "Transports food to stomach", location: "Throat", color: "#FFB347" },
  stomach: { name: "Stomach", function: "Digestive organ", location: "Abdomen", color: "#FFB347" },
  smallIntestine: { name: "Small Intestine", function: "Absorbs nutrients", location: "Abdomen", color: "#77DD77" },
  appendix: { name: "Appendix", function: "Immune function", location: "Abdomen", color: "#77DD77" },
  rectum: { name: "Rectum", function: "Stores feces", location: "Pelvis", color: "#AEC6CF" },
  anus: { name: "Anus", function: "Excretes feces", location: "Pelvis", color: "#AEC6CF" },
  duodenum: { name: "Duodenum", function: "First part of small intestine", location: "Abdomen", color: "#77DD77" },
  liver: { name: "Liver", function: "Detoxifies chemicals and produces bile", location: "Abdomen", color: "#77DD77" },
  galbladder: { name: "Gall Bladder", function: "Stores bile", location: "Abdomen", color: "#77DD77" },
  salivaryGland: { name: "Salivary Gland", function: "Produces saliva", location: "Mouth", color: "#FF6961" },
  colon: { name: "Colon", function: "Absorbs water and electrolytes", location: "Abdomen", color: "#77DD77" },
  urinaryBladder: { name: "Urinary Bladder", function: "Stores urine", location: "Pelvis", color: "#AEC6CF" },
  prostate: { name: "Prostate", function: "Produces seminal fluid", location: "Pelvis", color: "#CBAACB" },
  skeletalMuscle: { name: "Skeletal Muscle", function: "Movement", location: "Whole body", color: "#D1B280" },
  adipose: { name: "Adipose Tissue", function: "Stores fat", location: "Whole body", color: "#F5DEB3" },
  skin: { name: "Skin", function: "Protects body", location: "Whole body", color: "#FFE4C4" },
};

export default organData;
